### ISSUE TITLE
Move to JSON3?

### ISSUE THREAD

**Issue by aviks** [glitzflitz/JsonDB.jl#1]
Hey, @glitzflitz, this is a cool package, excited to see where it goes. 

I had a suggestion -- the JSON2 package is not going to be maintained for long, it would be better to move to JSON3.jl

**Comment by glitzflitz** [comment]
@aviks Thanks for the suggestion. I'll push new version with JSON3.jl

**Comment by glitzflitz** [comment]
Added JSON3 support in 14b6180ebfedd0b66a6c8f665f10786b6511e7af
